# Generated by Django 5.2.7 on 2025-11-26 15:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='商品名称')),
                ('brand', models.CharField(max_length=100, verbose_name='品牌')),
                ('category', models.CharField(max_length=50, verbose_name='分类(水/乳/精华)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('image_url', models.URLField(max_length=500, verbose_name='图片链接')),
                ('ingredients', models.TextField(help_text='用于AI分析', verbose_name='核心成分')),
                ('efficacy', models.CharField(help_text='如：保湿,抗衰,美白', max_length=255, verbose_name='功效标签')),
                ('suitable_skin', models.CharField(default='all', help_text='用于规则过滤', max_length=50, verbose_name='适用肤质')),
                ('rating_avg', models.FloatField(default=0.0, verbose_name='平均评分')),
                ('sales_count', models.IntegerField(default=0, verbose_name='销量')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('skin_type', models.CharField(choices=[('oil', '油性皮肤'), ('dry', '干性皮肤'), ('sensitive', '敏感肌肤'), ('combination', '混合性皮肤'), ('normal', '中性皮肤')], default='normal', max_length=20, verbose_name='肤质类型')),
                ('age_group', models.IntegerField(default=20, verbose_name='年龄段')),
                ('allergens', models.CharField(blank=True, max_length=255, null=True, verbose_name='过敏源(逗号分隔)')),
                ('is_profile_completed', models.BooleanField(default=False, verbose_name='画像是否完善')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户画像',
                'verbose_name_plural': '用户画像',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField(verbose_name='用户提问')),
                ('ai_response', models.TextField(verbose_name='AI回答')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI对话日志',
            },
        ),
        migrations.CreateModel(
            name='RecommendationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='推荐匹配度')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='AI推荐理由')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('view', '浏览'), ('click', '点击'), ('fav', '收藏'), ('rate', '评分'), ('buy', '购买')], max_length=10, verbose_name='交互类型')),
                ('score', models.FloatField(default=0.0, verbose_name='评分权重(1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户交互记录',
                'unique_together': {('user', 'product', 'type')},
            },
        ),
    ]
