# Generated by Django 5.2.7 on 2026-02-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendationresult",
            name="click_count",
            field=models.IntegerField(default=0, verbose_name="点击次数"),
        ),
        migrations.AddField(
            model_name="recommendationresult",
            name="view_count",
            field=models.IntegerField(default=0, verbose_name="展示次数"),
        ),
    ]
