# Generated by Django 5.2.7 on 2026-02-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_recommendationresult_click_count_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatlog",
            options={"verbose_name": "AI对话日志", "verbose_name_plural": "AI对话日志"},
        ),
        migrations.AddField(
            model_name="chatlog",
            name="completion_tokens",
            field=models.IntegerField(default=0, verbose_name="生成Token"),
        ),
        migrations.AddField(
            model_name="chatlog",
            name="corrected_response",
            field=models.TextField(blank=True, null=True, verbose_name="人工纠偏结果"),
        ),
        migrations.AddField(
            model_name="chatlog",
            name="is_corrected",
            field=models.BooleanField(default=False, verbose_name="是否已纠偏"),
        ),
        migrations.AddField(
            model_name="chatlog",
            name="latency_ms",
            field=models.IntegerField(default=0, verbose_name="响应延迟(ms)"),
        ),
        migrations.AddField(
            model_name="chatlog",
            name="prompt_tokens",
            field=models.IntegerField(default=0, verbose_name="提示词Token"),
        ),
        migrations.AddField(
            model_name="chatlog",
            name="total_tokens",
            field=models.IntegerField(default=0, verbose_name="总消耗Token"),
        ),
    ]
